language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: t3z1NFHVDG8HGs8cLs7QjVqRk7RjI7kmKAc/sUramuFGTpXdPZ2aEX+ZLEz/3EBCckQ7jbNF4EveiUzSuxQLc4CJ86hQltYp4XOVxO8t0Il+lnXx/ryO2K54wPr4B6G6dpDBwRb1R7T/fYDZUNGyzv3nv4+Vfg5W86eL1rbXRmbqYUvTjULFUBY/s6p+tT5Odjo3Fq4XZ1x93ItWL13/tqolPXB43joydX6b8uc4du9tT6dBLhPulU2ceyGxm0TPipvdQkEdL+ZCsdsczxDPmMg8PYqmPYcTFsXRQIvnzyI8dRHLqmWi/H6DV5Et1b/VwQN79ojb54gFoR6m56vl/sQn0fpRYXRdoT7kzf/d/wpUSwGp5qi3Vmo67TT2owrZeCxE2e6oQIlDxF4bThqfVZRr+h41yiLN7vsCGoBd/GH2HzHI3XqDGiC/h+3eBK6wMmekcTzEGPVqCzHmaW04reJMjrxBldX+XoKzhQMxbQNjMirW97z2QcZ4SJVsyVCzrx8q+2k2kQuNoe3c1QJPG6PIks1B/ffj/po/GXpduL8x9cbJhwNGLetsp9esMSE30C8gxBPH9Y9/XQ7jWnbU89yhdGuj/O2tfjyu1HeDe0SG32T2Rb0CDMNH1dml6b0GwJdDu8ZJCs/suA/wOLo7e6l/eMlTpByqplKpPO57lEk=
