language: node_js
node_js:
- node
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: YP52GeKHvw/jpac5L3Mi/nffLouEAf5gYvsT0FZjczEfkkaUus+ng6t5njLnG6WftLEUZ3SjiImBtYypIpv84gLckPW/5hxvDIDnMCck9856MSl8XQBrlLM4YEk59PUqZj7fGYrBSiK8wcyUyfxeKLccZFaD1EzGCzkKEvBMcpIFo1jVp1UzNuJ5xwZOfKXo9P67IhZQHBmjE+otYasMzjhd2cvBlAupn/G/RO1MI4oCbUOHPcdX1IBD3r9iJMpd6K8dlnqjqH43lVt8NMs5B3MVNfZRusGGxvXHwSHRQAhWG70gEjLrwQ6KyR2jf6otox8ZRDVzrNA4ovcZgQzoPEan9LuDm1FpakXXd5NXWKPj4evtnYlfbR241tKRifji2vBC93mdz6ROOa3ZMBDX4RJuoDZXpk3MqynKkMeoTIRss6tSzZdQQ3ijHKF2IC47DuOqHAUWriikCYEk31P8YMUdPujX8PN0SZhUf6wo4e7komi+9j9oyoLwbLnioLf/RsNl4FB9QOdKcDwAucvUONYXE2gDswcYsc6RUhX2TMLAEkXr1yirNVoLLZhyWmxjf4pPNITAOm+NTAOGTFl0PKTUWcy5eXd7tzGVDleSu7fFD9KRKvvA3AGTJyJHBYijQsB0uAFpoiM+b6iDNAKxAHvRRTCsNkYHH6yVADDg9B4=
  app: retrobox-web
  on:
    repo: Fruitseller/retrobox-web
